-- Seed the courses table with the full MBA-Executive catalog
-- Run this in the Supabase SQL Editor after schema.sql

insert into public.courses (code, name, semester, kind, area) values
  -- Semester 1 Core
  ('MBAEX-8101', 'Organizational Behavior', 1, 'core', null),
  ('MBAEX-8102', 'Data Analysis and Optimization', 1, 'core', null),
  ('MBAEX-8103', 'Managerial Economics', 1, 'core', null),
  ('MBAEX-8104', 'Accounting for Managerial Decisions', 1, 'core', null),
  ('MBAEX-8105', 'Marketing Management', 1, 'core', null),
  ('MBAEX-8106', 'Managerial Finance', 1, 'core', null),
  ('MBAEX-8107', 'Information Technology for Organizations', 1, 'core', null),
  -- Semester 2 Core
  ('MBAEX-8201', 'Human Resource Management', 2, 'core', null),
  ('MBAEX-8202', 'Operations Management for Executives', 2, 'core', null),
  ('MBAEX-8203', 'Economic Environment of Business', 2, 'core', null),
  ('MBAEX-8204', 'Strategic Financial Management', 2, 'core', null),
  ('MBAEX-8205', 'Marketing Research', 2, 'core', null),
  ('MBAEX-8206', 'Business Communication', 2, 'core', null),
  ('MBAEX-8207', 'Delivering Information Services', 2, 'core', null),
  -- Semester 3 Core
  ('MBAEX-8301', 'Business Ethics and Corporate Governance', 3, 'core', null),
  ('MBAEX-8302', 'Strategic Analysis', 3, 'core', null),
  ('MBAEX-8303', 'Sustainable Business and Development', 3, 'core', null),
  -- Semester 4 Core
  ('MBAEX-8401', 'Global Business Management', 4, 'core', null),
  ('MBAEX-8402', 'Legal Environment of Business', 4, 'core', null),
  ('MBAEX-8403', 'Leadership and Change Management', 4, 'core', null),
  ('MBAEX-8404', 'Strategic Management', 4, 'core', null),
  -- Electives: Culture, Philosophy & Management
  ('MBAEX-9101', 'Cultural, Philosophical and Spiritual Foundations of Management', null, 'elective', 'Culture, Philosophy & Management'),
  ('MBAEX-9102', 'Value Based Leadership: Learning to Create High Performing Organizations', null, 'elective', 'Culture, Philosophy & Management'),
  ('MBAEX-9103', 'Personal Power and Leadership through Asian Values', null, 'elective', 'Culture, Philosophy & Management'),
  -- Electives: Economics & Public Policy
  ('MBAEX-9201', 'Economic Growth and Development', null, 'elective', 'Economics & Public Policy'),
  ('MBAEX-9202', 'Economics of Innovation', null, 'elective', 'Economics & Public Policy'),
  -- Electives: Entrepreneurship
  ('MBAEX-9301', 'Entrepreneurship, Creativity and Innovation', null, 'elective', 'Entrepreneurship'),
  ('MBAEX-9302', 'Managing Human Resources for SMEs and Start-ups', null, 'elective', 'Entrepreneurship'),
  -- Electives: Finance
  ('MBAEX-9401', 'Quantitative Analysis of Financial Decisions', null, 'elective', 'Finance'),
  ('MBAEX-9402', 'Security Analysis and Portfolio Management', null, 'elective', 'Finance'),
  ('MBAEX-9403', 'Financial Markets and Institutions', null, 'elective', 'Finance'),
  ('MBAEX-9404', 'International Financial Management', null, 'elective', 'Finance'),
  ('MBAEX-9405', 'Merchant Banking and Financial Services', null, 'elective', 'Finance'),
  ('MBAEX-9406', 'Management Control System', null, 'elective', 'Finance'),
  ('MBAEX-9407', 'Corporate Taxation', null, 'elective', 'Finance'),
  ('MBAEX-9408', 'Financial Derivatives', null, 'elective', 'Finance'),
  ('MBAEX-9409', 'Project Planning, Analysis, and Management', null, 'elective', 'Finance'),
  ('MBAEX-9410', 'Financial Risk Management', null, 'elective', 'Finance'),
  ('MBAEX-9411', 'Fixed Income Securities', null, 'elective', 'Finance'),
  ('MBAEX-9412', 'Financial Analytics', null, 'elective', 'Finance'),
  ('MBAEX-9413', 'Mergers and Corporate Restructuring', null, 'elective', 'Finance'),
  ('MBAEX-9414', 'Financial Reporting', null, 'elective', 'Finance'),
  -- Electives: IT Management
  ('MBAEX-9501', 'Business Process Re-engineering', null, 'elective', 'IT Management'),
  ('MBAEX-9502', 'Strategic Management of Information Technology', null, 'elective', 'IT Management'),
  ('MBAEX-9503', 'Managing E-Business', null, 'elective', 'IT Management'),
  -- Electives: Marketing
  ('MBAEX-9601', 'Consumer Behaviour', null, 'elective', 'Marketing'),
  ('MBAEX-9602', 'Advertising Management', null, 'elective', 'Marketing'),
  ('MBAEX-9603', 'Competitive Marketing', null, 'elective', 'Marketing'),
  ('MBAEX-9604', 'Business Marketing', null, 'elective', 'Marketing'),
  ('MBAEX-9605', 'Sales Force Management', null, 'elective', 'Marketing'),
  ('MBAEX-9606', 'Service Marketing', null, 'elective', 'Marketing'),
  ('MBAEX-9607', 'Sales Promotion Management', null, 'elective', 'Marketing'),
  ('MBAEX-9608', 'Brand Management', null, 'elective', 'Marketing'),
  ('MBAEX-9609', 'Digital Marketing', null, 'elective', 'Marketing'),
  ('MBAEX-9610', 'Retailing Management', null, 'elective', 'Marketing'),
  ('MBAEX-9611', 'Marketing Channel', null, 'elective', 'Marketing'),
  ('MBAEX-9612', 'Marketing Analytics', null, 'elective', 'Marketing'),
  ('MBAEX-9613', 'Advanced Marketing Research', null, 'elective', 'Marketing'),
  ('MBAEX-9614', 'Global Marketing', null, 'elective', 'Marketing'),
  -- Electives: OB & HRM
  ('MBAEX-9701', 'Human Resource Metrics and Analytics', null, 'elective', 'OB & HRM'),
  ('MBAEX-9702', 'Performance Management and Training Interventions', null, 'elective', 'OB & HRM'),
  ('MBAEX-9703', 'Managing Training, Learning and Development', null, 'elective', 'OB & HRM'),
  ('MBAEX-9704', 'Negotiation and Influence Skills', null, 'elective', 'OB & HRM'),
  ('MBAEX-9705', 'Compensation and Rewards Management', null, 'elective', 'OB & HRM'),
  ('MBAEX-9706', 'Management of Industrial Relations', null, 'elective', 'OB & HRM'),
  ('MBAEX-9707', 'Cross Cultural and Global Management', null, 'elective', 'OB & HRM'),
  ('MBAEX-9708', 'Managing Interpersonal and Group Processes', null, 'elective', 'OB & HRM'),
  ('MBAEX-9709', 'Managing Diversity', null, 'elective', 'OB & HRM'),
  ('MBAEX-9710', 'Counselling Skills for Managers', null, 'elective', 'OB & HRM'),
  ('MBAEX-9711', 'Human Resource Development: Strategies and Systems', null, 'elective', 'OB & HRM'),
  ('MBAEX-9712', 'Change and Intervention Strategies', null, 'elective', 'OB & HRM'),
  ('MBAEX-9713', 'Talent Management', null, 'elective', 'OB & HRM'),
  ('MBAEX-9714', 'Organizational Leadership: Inspiration, Dilemmas and Action', null, 'elective', 'OB & HRM'),
  -- Electives: Operations & Decision Sciences
  ('MBAEX-9801', 'Operations Strategy', null, 'elective', 'Operations & Decision Sciences'),
  ('MBAEX-9802', 'Total Quality Management for Business Excellence', null, 'elective', 'Operations & Decision Sciences'),
  ('MBAEX-9803', 'Systems Optimization and Management Science', null, 'elective', 'Operations & Decision Sciences'),
  ('MBAEX-9804', 'Supply Chain Management', null, 'elective', 'Operations & Decision Sciences'),
  ('MBAEX-9805', 'Predictive Analytics and Big Data', null, 'elective', 'Operations & Decision Sciences'),
  ('MBAEX-9806', 'World Class Manufacturing', null, 'elective', 'Operations & Decision Sciences'),
  ('MBAEX-9807', 'Supply Chain Analytics', null, 'elective', 'Operations & Decision Sciences'),
  ('MBAEX-9808', 'Integrated Management Systems', null, 'elective', 'Operations & Decision Sciences'),
  ('MBAEX-9809', 'Technology, Innovation and New Product Management', null, 'elective', 'Operations & Decision Sciences'),
  ('MBAEX-9810', 'Service Operations Management', null, 'elective', 'Operations & Decision Sciences'),
  ('MBAEX-9811', 'Sustainable Operations Management', null, 'elective', 'Operations & Decision Sciences'),
  ('MBAEX-9812', 'Artificial Intelligence and Deep Learning', null, 'elective', 'Operations & Decision Sciences'),
  ('MBAEX-9813', 'Managerial Decision Modelling', null, 'elective', 'Operations & Decision Sciences'),
  -- Electives: Strategy
  ('MBAEX-9901', 'Strategic Capability Building and Innovation', null, 'elective', 'Strategy'),
  ('MBAEX-9902', 'Strategic Management in Social Enterprises', null, 'elective', 'Strategy'),
  ('MBAEX-9903', 'International Business Strategy', null, 'elective', 'Strategy'),
  ('MBAEX-9904', 'Strategic Management of Start-ups', null, 'elective', 'Strategy'),
  -- Project Study
  ('MBAEX-9907', 'Project Study', null, 'elective', 'Project Study')
on conflict (code) do nothing;
